[project]
name = "web-researcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Prishanga Prayus Bora", email = "prishanga1@gmail.com" }
]
requires-python = ">=3.11,<3.12"
dependencies = [
    "arize-phoenix>=14.10.0",
    "beautifulsoup4>=4.15.0",
    "crewai>=1.15.22",
    "ddgs>=9.14.4",
    "ipykernel>=7.3.0",
    "langchain>=1.4.2",
    "langchain-ollama>=1.1.0",
    "playwright>=1.62.0",
    "trafilatura>=2.2.0",
]

[project.scripts]
web-researcher = "web_researcher:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
